function [ S11, S12, S22 ] = calcErrorBox( xo, xs, xm, Glo, Gls, Glm )
%    S22 = ((1/xm-Gm/Go*1/xo)*(1-Gs/Go) + (Gs/Go*1/xo-1/xm)*(1-Gm/Go)) / ...
%        (Gs*(1/xo-1/xs)*(1-Gm/Go)-Gm*(1/xo-1/xm)*(1-Gs/Go));
%    S11 = (1/xm - Gm/Go*1/xo + S22*Gm*(1/xo-1/xm)) / ...
%        (1 - Gm/Go);
%    S12 = 1/(Go*xo) - S22*1/xo - S11*1/Go + S11*S22;
S11 = -((Glm - Glo)*Gls*xs + (Glm*Glo - Glm*Gls)*xm - (Glm*Glo - ...
Glo*Gls)*xo)/((Glm - Glo)*Gls*xm*xo - ((Glm*Glo - Glo*Gls)*xm - (Glm*Glo ...
- Glm*Gls)*xo)*xs);

S12 = -((Glm^2*Glo - Glm*Glo^2 + (Glm - Glo)*Gls^2 - (Glm^2 - ...
Glo^2)*Gls)*xm^2*xo - (Glm^2*Glo - Glm*Glo^2 + (Glm - Glo)*Gls^2 - ...
(Glm^2 - Glo^2)*Gls)*xm*xo^2 + ((Glm^2*Glo - Glm*Glo^2 + (Glm - ...
Glo)*Gls^2 - (Glm^2 - Glo^2)*Gls)*xm - (Glm^2*Glo - Glm*Glo^2 + (Glm - ...
Glo)*Gls^2 - (Glm^2 - Glo^2)*Gls)*xo)*xs^2 - ((Glm^2*Glo - Glm*Glo^2 + ...
(Glm - Glo)*Gls^2 - (Glm^2 - Glo^2)*Gls)*xm^2 - (Glm^2*Glo - Glm*Glo^2 + ...
(Glm - Glo)*Gls^2 - (Glm^2 - Glo^2)*Gls)*xo^2)*xs)/((Glm^2 - 2*Glm*Glo + ...
Glo^2)*Gls^2*xm^2*xo^2 + ((Glm^2*Glo^2 - 2*Glm*Glo^2*Gls + ...
Glo^2*Gls^2)*xm^2 - 2*(Glm^2*Glo^2 + Glm*Glo*Gls^2 - (Glm^2*Glo + ...
Glm*Glo^2)*Gls)*xm*xo + (Glm^2*Glo^2 - 2*Glm^2*Glo*Gls + ...
Glm^2*Gls^2)*xo^2)*xs^2 + 2*(((Glm*Glo - Glo^2)*Gls^2 - (Glm^2*Glo - ...
Glm*Glo^2)*Gls)*xm^2*xo - ((Glm^2 - Glm*Glo)*Gls^2 - (Glm^2*Glo - ...
Glm*Glo^2)*Gls)*xm*xo^2)*xs);

S22 = ((Glm - Glo)*xm*xo - ((Glm - Gls)*xm - (Glo - Gls)*xo)*xs)/((Glm ...
- Glo)*Gls*xm*xo - ((Glm*Glo - Glo*Gls)*xm - (Glm*Glo - Glm*Gls)*xo)*xs);

end

