function [S11,S12,S22] = calcErrorBoxM(xo,xs,xm,Go,Gs,Gm)
S11=(Gm.*Go.*xm+(-1).*Gm.*Gs.*xm+(-1).*Gm.*Go.*xo+Go.*Gs.*xo+Gm.*Gs.*xs+(-1) ...
  .*Go.*Gs.*xs).*((-1).*Gm.*Gs.*xm.*xo+Go.*Gs.*xm.*xo+Gm.*Go.*xm.*xs+(-1) ...
  .*Go.*Gs.*xm.*xs+(-1).*Gm.*Go.*xo.*xs+Gm.*Gs.*xo.*xs).^(-1);
S12=(-1).*(Go+(-1).*Gs).*(Gm.^2+(-1).*Gm.*Go+(-1).*Gm.*Gs+Go.*Gs).*(xo+(-1) ...
  .*xs).*(xm.^2+(-1).*xm.*xo+(-1).*xm.*xs+xo.*xs).*(Gm.^2.*Gs.^2.*xm.^2.* ...
  xo.^2+(-2).*Gm.*Go.*Gs.^2.*xm.^2.*xo.^2+Go.^2.*Gs.^2.*xm.^2.*xo.^2+(-2) ...
  .*Gm.^2.*Go.*Gs.*xm.^2.*xo.*xs+2.*Gm.*Go.^2.*Gs.*xm.^2.*xo.*xs+2.*Gm.* ...
  Go.*Gs.^2.*xm.^2.*xo.*xs+(-2).*Go.^2.*Gs.^2.*xm.^2.*xo.*xs+2.*Gm.^2.* ...
  Go.*Gs.*xm.*xo.^2.*xs+(-2).*Gm.*Go.^2.*Gs.*xm.*xo.^2.*xs+(-2).*Gm.^2.* ...
  Gs.^2.*xm.*xo.^2.*xs+2.*Gm.*Go.*Gs.^2.*xm.*xo.^2.*xs+Gm.^2.*Go.^2.* ...
  xm.^2.*xs.^2+(-2).*Gm.*Go.^2.*Gs.*xm.^2.*xs.^2+Go.^2.*Gs.^2.*xm.^2.* ...
  xs.^2+(-2).*Gm.^2.*Go.^2.*xm.*xo.*xs.^2+2.*Gm.^2.*Go.*Gs.*xm.*xo.*xs.^2+ ...
  2.*Gm.*Go.^2.*Gs.*xm.*xo.*xs.^2+(-2).*Gm.*Go.*Gs.^2.*xm.*xo.*xs.^2+ ...
  Gm.^2.*Go.^2.*xo.^2.*xs.^2+(-2).*Gm.^2.*Go.*Gs.*xo.^2.*xs.^2+Gm.^2.* ...
  Gs.^2.*xo.^2.*xs.^2).^(-1);
S22=(Gm.*xm.*xo+(-1).*Go.*xm.*xo+(-1).*Gm.*xm.*xs+Gs.*xm.*xs+Go.*xo.*xs+(-1) ...
  .*Gs.*xo.*xs).*(Gm.*Gs.*xm.*xo+(-1).*Go.*Gs.*xm.*xo+(-1).*Gm.*Go.*xm.* ...
  xs+Go.*Gs.*xm.*xs+Gm.*Go.*xo.*xs+(-1).*Gm.*Gs.*xo.*xs).^(-1);
end
